name: test
channels:
  - conda-forge
dependencies:
- python

# required
- matplotlib
- numpy
- pandas
- scikit-learn
- networkx 
- pint
- pip 
- geoalchemy2 
- osmnx 
- psycopg2
- tqdm
- similaritymeasures
- jupyter
- geopandas>=0.10.0
- shapely<=1.8.5
- pygeos>=0.10.0

# tests
- pytest
- pytest-cov
- pytest-xdist

  
