name: test
channels:
  - conda-forge
dependencies:
- python
- numpy
- matplotlib
- geopandas>=1.1.0
- scikit-learn
- pip
- geoalchemy2
- osmnx>=2.0.0
- psycopg2
- tqdm
- similaritymeasures
- jupyter

# tests
- pytest
- pytest-cov
- pytest-xdist
