name: test
channels:
  - conda-forge
  - defaults
dependencies:
- matplotlib
- numpy
- pandas<=1.2.5
- geopandas
- scikit-learn
- networkx 
- pint
- pip 
- geoalchemy2 
- osmnx 
- psycopg2
- pytest
- pytest-cov
- pytest-xdist
- tqdm
- similaritymeasures
- pygeos
- jupyter
