name: test
channels:
  - conda-forge
dependencies:
  - notebook
  # other envs
  - numpy
  - scikit-learn
  - matplotlib
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - geoalchemy2 
  - osmnx 
  - psycopg2
  - tqdm
  - similaritymeasures
  - scikit-learn
  - networkx 
  - pint  
  # required
  - pandas
  - shapely
  - fiona
  - pyproj
  - pygeos
  - packaging
  - geopandas
  - rtree
  - mapclassify
  - folium
  - xyzservices
  - scipy
  - geopy
  - SQLalchemy
  - libspatialite
  - pyarrow