name: test
channels:
  - conda-forge
dependencies:
- matplotlib
- numpy
- pandas<=1.2.5
- geopandas
- scikit-learn
- networkx 
- pint
- pip 
- geoalchemy2 
- osmnx 
- psycopg2
- tqdm
- similaritymeasures
- pygeos
- jupyter

# tests
- pytest
- pytest-cov
- pytest-xdist

  
