name: autoupdate
on:
  # This will trigger on all pushes to all branches.
  push: 
    branches: 
      - master
      - autoupdate_workflow
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_MSG: "The branch was auto updated"
